  name: Push into main branch
  on:
    push:
      branches: [ master ]


  jobs:
    context:
      if: github.event_name == 'pull_request' && github.event.action == 'closed' && github.event.pull_request.merged == true
      runs-on: ubuntu-latest
      steps:

      - name: pull request
        if: github.event_name == 'pull_request' && github.event.action == 'closed' && github.event.pull_request.merged == true

      - name: Checkout
        uses: actions/checkout@v3

      - name: Build
        id: build
        uses: cloudposse/github-action-docker-build-push@main
        with:
          registry: registry.hub.docker.com
          organization: "${{ github.event.repository.owner.login }}"
          repository: "yohane0w0"
          login: "${{ secrets.DOCKERHUB_USERNAME }}"
          password: "${{ secrets.DOCKERHUB_PASSWORD }}"
          platforms: linux/amd64,linux/arm64
          
      - run: echo "Build Docker & Push Image Success🎉"    

      outputs:
        image: ${{ steps.build.outputs.image }}
        tag: ${{ steps.build.outputs.tag }}

